var masterDeckList = {
"deckListPlayer1": [
    {"deckName":"Adun Oakenshield", "deckColor":"BRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Age of Ice", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Snow"},
    {"deckName":"Allies Aplenty", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Alms for the Cure", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ancestors", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Spirits"},
    {"deckName":"Angel's Grace", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Atog Atog", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Attack of the Clones", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Auroch Herd", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Balthazor's Groupies", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Ladies"},
    {"deckName":"Balthazor's Minions", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Balthor's Minions", "deckColor":"B", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":"Zombies"},
    {"deckName":"aBaru for You", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Beatdown for Hire", "deckColor":"B", "deckFormat":"Commander", "deckCards":100 , "deckRank":"D", "deckNotes":"Mercenaries"},
    {"deckName":"Beeble Beatdown", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Big Blue", "deckColor":"U", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Big Green", "deckColor":"G", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Big White", "deckColor":"W", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Bird is the Word", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Blight of the Fens", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Bling", "deckColor":"WBG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Blitz Kreig", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Blood Carnival", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Bones", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":"Skeletons"},
    {"deckName":"Brain Scramble", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":"Shocker"},
    {"deckName":"Bruna", "deckColor":"WU", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Built From Scratch", "deckColor":"R", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Bump in the Night", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Nightstalkers"},
    {"deckName":"Burn the Earth", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Burning Fury of a Thousand Suns", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Champions of the Pit - Initiation Deck", "deckColor":"WBR", "deckFormat":"Initiation", "deckCards":80 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Chaos Reigns", "deckColor":"WUBRG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Chatter of the Squirrel", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Cheap Goblins", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Chill Pauper", "deckColor":"WU", "deckFormat":"Casual Pauper", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Circle of Life", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Dragon Spirits"},
    {"deckName":"Color in the Beatdown", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Scarecrow"},
    {"deckName":"Combat Mastery", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Flanking"},
    {"deckName":"Counter Punch", "deckColor":"UBG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Coven of Nine", "deckColor":"WUBR", "deckFormat":"Casual", "deckCards":80 , "deckRank":"C", "deckNotes":"Witches"},
    {"deckName":"Crab People", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Crackling Goblins", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Crazy Goblins", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Crazy Train", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Croaking Goblins", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Crunchy Goblins", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Cult of Nefarox", "deckColor":"B", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Cunning Vs", "deckColor":"WUR", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Dakkon Blackblade", "deckColor":"WUB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Damage for Breakfast", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Darien's Legacy", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Dark Devotion", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Deal With the Devil", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Deathklok", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Deckmaster Jon Finkel", "deckColor":"BR", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Deckmaster Richard Garfield", "deckColor":"RG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Democratic Conspiracy", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Denial of Will", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Devour for Power", "deckColor":"WBG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Diaoshan Artful Beauty", "deckColor":"R", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Doom Men of the Moon", "deckColor":"WURG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Double or Nothing", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Dragon Fury", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":"Dragon Storm"},
    {"deckName":"Dragon Mountain", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Dragon's Horde", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Drop of Daylight", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Sunburst"},
    {"deckName":"Dwarven Thunder", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Elves of Fury", "deckColor":"URG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Elves of the Chosen", "deckColor":"G", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Elves Vs", "deckColor":"G", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Empire Strikes Back", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"End of the World", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Enter Shahrazad", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Erupt and Overwhelm", "deckColor":"R", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Eternal Bargain", "deckColor":"WUB", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Evade and Shimmer", "deckColor":"WU", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Evasive Maneuvers", "deckColor":"WUG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Everything Burns", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Evil Eye", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Exsanguimator", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Fall of Troy", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Fat Cobra", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Ferngully's Payback", "deckColor":"UBG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Float like a Butterfly Sting like a Bee", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"For Honor and Valor", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"",},
    {"deckName":"For the Cause", "deckColor":"W", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":"Rebels"},
    {"deckName":"Forged in Stone", "deckColor":"W", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Frankenstein", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Frankie's Question", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ghave's Growth", "deckColor":"WBG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Gin", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Goblins Vs", "deckColor":"R", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Golgari", "deckColor":"BG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Good Will", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":"Donate"},
    {"deckName":"Graveborn", "deckColor":"WUBRG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Great Forest Emergence", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Green Acres", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Green Beets", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Green Giant", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Green Manaburn", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Guardians of the Muck", "deckColor":"WUBG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Guardians of the Wild", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Druids"},
    {"deckName":"Guided By Nature", "deckColor":"G", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Hakunin", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":"Shamans"},
    {"deckName":"Happy Days", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Hazezom Tamar", "deckColor":"WRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Heavenly Inferno", "deckColor":"WBR", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Hidden Phoenix", "deckColor":"WRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hippie Denial", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Hive's Breath", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Crusade", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Diversity", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Growth", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Neglect", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Rage", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hive's Shadow", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Holy Crusade", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Holy Relics", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Honden of The Myojin", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"House of Pain by George Baxter", "deckColor":"BRG", "deckFormat":"Casual Preconstructed", "deckCards":80 , "deckRank":"B", "deckNotes":""},
    {"deckName":"I am Legend", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ice Kitten", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ice Scraper", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"iSpell", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"It Came From the Malestrom", "deckColor":"URG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ivy League", "deckColor":"U", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":"Wizards"},
    {"deckName":"Izzet", "deckColor":"UR", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Jhoira", "deckColor":"UR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"John's Modern", "deckColor":"WRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"John's Ocean Critters", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Juicy Fruit", "deckColor":"WUBRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":"Planeswalkers"},
    {"deckName":"Junkyard", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Justin Sane", "deckColor":"N", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":"Myr"},
    {"deckName":"Justin Time", "deckColor":"N", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Karona", "deckColor":"WUBRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Knowledge is Power", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Life Not Unlived", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Shapeshifter"},
    {"deckName":"Light and Fury", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Lim-Dul's Oasis", "deckColor":"BRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Mad Scientist", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Madara Uchia Clan", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Marath", "deckColor":"WRG", "deckFormat":"Commander Tiny Leader", "deckCards":100 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Maraxus", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Master of the Slaves", "deckColor":"WUBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Mavrick", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Medic!", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Mermaider", "deckColor":"WU", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Michael's Affinity", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":80 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Michael's Dragons", "deckColor":"BRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Michael's Madness", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Michael's Norin", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Michael's Psychatog", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Michael's Reanimator", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Michael's Slivers", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Michael's Tezzeret", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Michael's Zombies", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Minamo Namikaze Clan", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Mind Boggle", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Mind Fog", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Mind Seize", "deckColor":"UBR", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Mirror Mastery", "deckColor":"URG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Mirror Mirror", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Miscalculation", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Mishra", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Monkey Business", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Monks Of The Full Palm", "deckColor":"URG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Mythical Proportions", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Nantuko Knights", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Nath", "deckColor":"BG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Nature of the Beast", "deckColor":"WRG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Nick's Illusionary Dreadnought", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Night of the Ninja", "deckColor":"UB", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Nightmare's Reward", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Niv-Mizzet", "deckColor":"UR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Niv's Rage", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Norin", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Northern Horde", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Obsessive Madness", "deckColor":"BRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Octopie Buttkrakens and Serpents Oh My!", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"One For All", "deckColor":"WUBRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":"Changelings"},
    {"deckName":"Orc Hordes", "deckColor":"WBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ordeals Aplenty", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Pack Hunt", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Wolves"},
    {"deckName":"Pain Scramble", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":"Shocker"},
    {"deckName":"Peer Through Time", "deckColor":"U", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Phyrexia", "deckColor":"B", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Pianna Roams", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Political Puppets", "deckColor":"WUR", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Polluted Minds", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Pon Farr", "deckColor":"UBR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":"Vampires"},
    {"deckName":"Power Hungry", "deckColor":"BRG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Primordial Hunger", "deckColor":"RG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Rabid Dancer", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rabid Wombat", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rafiq of the Many", "deckColor":"WUG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rage With the Machine", "deckColor":"WUBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ramirez DePietro", "deckColor":"UB", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rattlin Bog", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Recycled Life", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":"Thallids"},
    {"deckName":"Red Wizard's Doom", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Relentless Rats", "deckColor":"B", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Revenge of the Orb", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rohgahh", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":"Kobolds"},
    {"deckName":"Sands of Life", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Savage Auras", "deckColor":"WG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Scalpelexis Exists", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Scrambled Eggs", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Secret Scrolls", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Senju Hashirama Clan", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Serra Angel Speed Bump", "deckColor":"UBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Seven Seas", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Shady Business", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Siren Gwendlyn", "deckColor":"UBR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Siren Merieke Ri Berit", "deckColor":"WUB", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Siren Rubinia", "deckColor":"WUG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Sky is Falling", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Slip and Slide", "deckColor":"WUG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Slumgolem Casserole", "deckColor":"WUBG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Snakes on a Bow", "deckColor":"UBG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Sparkley Bits", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"SPECTRE", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Speed Vs", "deckColor":"WBR", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Spread the Sickness", "deckColor":"BRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Starre Night", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Stealthy Attack", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":"Morph"},
    {"deckName":"Stewards of Kher", "deckColor":"BRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Summer Expedition", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Sworn to Darkness", "deckColor":"B", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Tamanoa Sunrise", "deckColor":"WRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Tetsuo Umezawa", "deckColor":"UBR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Texas Justice", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Angry Mob"},
    {"deckName":"That Deck", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"The Avengers", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"The Coalition", "deckColor":"WUBRG", "deckFormat":"Casual Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"The Hive", "deckColor":"WUBRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":"Slivers"},
    {"deckName":"Thriss", "deckColor":"G", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Tiamat", "deckColor":"WUBRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Tinkering Gnomes", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Top Gun", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Toshiro's Pact", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Tour De Jour", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Traitor's of Glissa", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Transformers", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Triumph of the Orb", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Trostani's Grove", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Trumpets of Peace", "deckColor":"W", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Trumpets of War", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Twisted Bramble Bugs", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Uril the Miststalker", "deckColor":"WRG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"War", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"War Never Changes", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Weezer", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Weird Science", "deckColor":"UBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Werewolf Pack", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"What Is Real?", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Whimsical Musings of Delight", "deckColor":"URG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"S", "deckNotes":"Squire of Balthazor"},
    {"deckName":"Who's The Bosh", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Wild BBQ", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Windseeker Hillbillies", "deckColor":"WRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Witch Hunt", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Wolf Pack", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Wombat Wannabe", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Wooz's Deck of Ooze", "deckColor":"UBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Wort", "deckColor":"BR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Yamazaki Clan", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Yellowstone", "deckColor":"WURG", "deckFormat":"Casual", "deckCards":80 , "deckRank":"C", "deckNotes":""},
    {"deckName":"You Only Live Twice", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Zedruu", "deckColor":"WUR", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Zuberi", "deckColor":"W", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""},
    {"deckName":"aZur the Enchanter", "deckColor":"WUB", "deckFormat":"Commander", "deckCards":100 , "deckRank":"C", "deckNotes":""}
],
"deckListPlayer2": [
    {"deckName":"66% of the Time it Works Every Time", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Justice and Fury", "deckColor":"WRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Ajani"},
    {"deckName":"Angels", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Assemble the Doomsday Machine", "deckColor":"WUB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"Bring About the Undead Apocalypse", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"Scorch the World with Dragonsfire", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"Trample Civilization Underfoot", "deckColor":"WG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"Army of Entropy", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Aura Masters", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Azorus Ascendant", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Back to the Graveyard", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Bailfire Liege", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"111 Barrage", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"aBattalion", "deckColor":"W", "deckFormat":"Casual", "deckCards":80 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Bestow upon You", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Big Blue", "deckColor":"UBG", "deckFormat":"Casual", "deckCards":85 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Big Red Blast Fest", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Blizak and Wizite", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Boggart's Feast", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Bogs Brew", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Bouncefest", "deckColor":"WUB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Bright Future", "deckColor":"B", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Broken the 20th Level of Enlightenment", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Burokku Sa Renal Seishin", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Buybacks A Bitch", "deckColor":"WBG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Burn and Destroy", "deckColor":"R", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Chandler Nalaar"},
    {"deckName":"Charmed Existense", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Cheap Artifacts", "deckColor":"WUBR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Code of the Orzhov", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Coalition", "deckColor":"WUBRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Command Your Creatures", "deckColor":"WG", "deckFormat":"Commander", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Evasive Maneuvers", "deckColor":"WUG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Eternal Bargain", "deckColor":"WUB", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Mirror Mastery", "deckColor":"URG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Nature of the Beast", "deckColor":"WRG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Peer Through Time", "deckColor":"W", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Power Hungry", "deckColor":"BRG", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Guided by Nature", "deckColor":"G", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Mindseize", "deckColor":"UBR", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Sworn to Darkness", "deckColor":"B", "deckFormat":"Commander Preconstructed", "deckCards":100 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Critical Mass", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Dark Cycle", "deckColor":"WB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Death March", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Demons", "deckColor":"B", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Dimir's Intrigues", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Dimir's Revenge", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Distorted Reality Pool", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Dragons", "deckColor":"R", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Elemental's Path", "deckColor":"WUBRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Elvish Predication", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Duty and Protection", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Elspeth Tirel"},
    {"deckName":"Everybody Dies", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Evolutions A Happin'", "deckColor":"BG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ev're Day I'm Shufflin'", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Eye of Distortion", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Fate", "deckColor":"UG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Flayer of the Hartbound", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Flippin' Crazy", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"From the Graveyard", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Fury", "deckColor":"R", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"George's Special Forces", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Goblin", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Going Rouge", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Golgari", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Green Slivers", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Grull Weilding", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ferocity and Growth", "deckColor":"G", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Guscloke", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Heath Nelson", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hero", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Hollow Ground", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Hope's Crusade", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"I Have Crabs", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ivory Doom", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Ixidor's Legacy", "deckColor":"U", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Izzet", "deckColor":"UR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Mind Over Matter", "deckColor":"U", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":"Jace"},
    {"deckName":"Mind Seize", "deckColor":"U", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Jace"},
    {"deckName":"Joe's Domination", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Knights", "deckColor":"WG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Erupt and Overwhenm", "deckColor":"R", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Koth"},
    {"deckName":"Kreatur Feature", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Kreatur Killa'", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Life 4 Death", "deckColor":"WR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Lift Off", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Little Bashers", "deckColor":"W", "deckFormat":"Casual", "deckCards":85 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Death and Ambition", "deckColor":"B", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":"Liliana Vess"},
    {"deckName":"Merfolk", "deckColor":"WU", "deckFormat":"Casual", "deckCards":70 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Monsters", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Monster's Tribute", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Mortal Coil", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"My Shitty Ass Affinity Deck", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Myr Oh My", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Son of Goblin", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Newfect", "deckColor":"UG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Avrice and Deceit", "deckColor":"UBR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Outside Chance", "deckColor":"URG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Phyrexia", "deckColor":"B", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Metallic Dreams", "deckColor":"WUBRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Chaos Reins", "deckColor":"WUBRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Elemental Thunder", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Night of the Ninja", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Primordial Hunger", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Savage Auras", "deckColor":"WG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":"Planeschase"},
    {"deckName":"Strikeforce", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Zombie Empire", "deckColor":"B", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Planeschase"},
    {"deckName":"Prelife Punch to the Face", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Premium Slivers", "deckColor":"WUBRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Foil"},
    {"deckName":"Profect", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Puppet Master", "deckColor":"G", "deckFormat":"Casual", "deckCards":70 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rancor's Bloodsport", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Razing Psyche", "deckColor":"UB", "deckFormat":"Casual", "deckCards":70 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Reality Escape Blade", "deckColor":"WUR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Rebels Unite", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Elemental Mastery", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Red Samurai", "deckColor":"R", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Rescue From the Underworld", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Ripples of Fun", "deckColor":"UR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Rituals of Rebirth", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Rose", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Sacrificial Bam", "deckColor":"BR", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Sacrificial Human", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Shamanism", "deckColor":"WBG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Sidestep", "deckColor":"UR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Simic Mutology", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Snakes Path", "deckColor":"G", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Son of Guscloke", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Soratimsi's Wisdom", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Hunt and Feed", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Sorin"},
    {"deckName":"Spawn of Eldrazi", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Spiritual Revolution", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Starvation of Hope", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"D", "deckNotes":""},
    {"deckName":"Sotrmkirk Nobles", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Super Abundance", "deckColor":"N", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Suspended Scentance", "deckColor":"UB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Swarm and Slam", "deckColor":"WG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Power and Secrecy", "deckColor":"U", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Tezzeret"},
    {"deckName":"Torment and Agonize", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":"Tibalt"},
    {"deckName":"Tourney Fect", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Twilight of the Fifth Dawn", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Twisted Copies of a Broken Reality", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":65 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Unholy Alliance", "deckColor":"WUBRG", "deckFormat":"Casual", "deckCards":65 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Unraveling Mind", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Urza's Empire", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Vanishing Hope", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Evade and Shimmer", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Venser"},
    {"deckName":"Dirty Work", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Varaska"},
    {"deckName":"Warrior's Code", "deckColor":"RG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Way of the Warrior", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"Wicked Big", "deckColor":"G", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Wicked Big's Even More Wicked Bigger Older Brother", "deckColor":"G", "deckFormat":"Casual", "deckCards":85 , "deckRank":"B", "deckNotes":""},
    {"deckName":"11th Hour (Check Color)", "deckColor":"UGR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Athiest's  Truth  (Check Color)", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Cunning", "deckColor":"WUR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Forgetful Explorer", "deckColor":"G", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Horde of the Dragons", "deckColor":"RU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Master Blaster", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Mill Oh My", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Paralyzing Peek Past Present Perils", "deckColor":"UR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Speed", "deckColor":"RWB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"Valiant Discord check color", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Wisest of All", "deckColor":"U", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Aeoa Paquete look up color", "deckColor":"UBR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"S", "deckNotes":""},
    {"deckName":"Power", "deckColor":"UBG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Profit", "deckColor":"BG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"Kiora", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"More 'Fang & Man' Fest", "deckColor":"UG", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"White Mocha", "deckColor":"W", "deckFormat":"Commander", "deckCards":60 , "deckRank":"B", "deckNotes":""}
],
"deckListPlayer3": [
    {"deckName":"PL 3 66% of the Time it Works Every Time", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"PL 3 Justice and Fury", "deckColor":"WRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Ajani"},
    {"deckName":"PL 3 Angels", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"", "deckAuthor": "John"},
    {"deckName":"PL 3 Assemble the Doomsday Machine", "deckColor":"WUB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 3 Bring About the Undead Apocalypse", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 3 Scorch the World with Dragonsfire", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 3 Trample Civilization Underfoot", "deckColor":"WG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 3 Army of Entropy", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 3 Aura Masters", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 3 Azorus Ascendant", "deckColor":"WU", "deckFormat":"Casual", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 3 Back to the Graveyard", "deckColor":"UB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 3 Bailfire Liege", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 3 Barrage", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 3 Battalion", "deckColor":"W", "deckFormat":"Casual", "deckCards":80 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 3 Bestow upon You", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 3 Big Blue", "deckColor":"UBG", "deckFormat":"Casual", "deckCards":85 , "deckRank":"A", "deckNotes":""}
],
"deckListPlayer4": [
    {"deckName":"PL 4 66% of the Time it Works Every Time", "deckColor":"R", "deckFormat":"Casual", "deckCards":60 , "deckRank":"C", "deckNotes":""},
    {"deckName":"PL 4 Justice and Fury", "deckColor":"WRG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Ajani"},
    {"deckName":"PL 4 Angels", "deckColor":"W", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 4 Assemble the Doomsday Machine", "deckColor":"WUB", "deckFormat":"Casual", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 4 Bring About the Undead Apocalypse", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 4 Scorch the World with Dragonsfire", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 4 Trample Civilization Underfoot", "deckColor":"WG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":"Archenemy"},
    {"deckName":"PL 4 Army of Entropy", "deckColor":"BR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 4 Aura Masters", "deckColor":"WU", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 4 Bailfire Liege", "deckColor":"WR", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 4 Barrage", "deckColor":"RG", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 4 Battalion", "deckColor":"W", "deckFormat":"Casual", "deckCards":80 , "deckRank":"A", "deckNotes":""},
    {"deckName":"PL 4 Bestow upon You", "deckColor":"WB", "deckFormat":"Preconstructed", "deckCards":60 , "deckRank":"B", "deckNotes":""},
    {"deckName":"PL 4 Big Blue", "deckColor":"UBG", "deckFormat":"Casual", "deckCards":85 , "deckRank":"A", "deckNotes":""}
]};

