//attack battle screen
//supply drop
//game ends


//Admin Settings
const adminSettings = {
    supportBonus: {
        defendingLife: 3.2,
        defendingHand: 1.2,
        defendingPower: 0.3,
        defendingToughness: 0.4,
        attackingLife: 2.2,
        attackingHand: 0.9,
        attackingPower: 0.2,
        attackingToughness: 0.3
    }
};

//Game Variables
var gameVars = {
    battleScreenInfo: {
        groundZero: "",
        battlePlayersCount: [],
        battleDecks: [],
        battleWinners: []
    },
    gameLog: [],
    globalGameOptions: {
        totalPlayers: 5,
        numberOfSupplyPointTypes: 3,
        numberOfRandomSupplyPoints: 2
    },
    gameStatus: {
        mode: "setup", //setup placement attack move
        focus: "setup", //setup map battle log
        turn: 1,
        turnOrder: [],
        currentAttack: 1,
        availableSupplyPoints: []
    },
    mapInfo: {
        mapSelect: [],
        possibleBattle: [],
        alreadyAttacked: [],
        countryList: [
            {countryName: 'Afghanistan', country: 'afghanistan', continent: 'Asia', color: 'G', borders: ['ural', 'china','india','middle-east','ukraine']},
            {countryName: 'Alaska', country: 'alaska', continent: 'North America', color: 'W', borders: ['kamchatka', 'northwest-territory','alberta']},
            {countryName: 'Alberta', country: 'alberta', continent: 'North America', color: 'W', borders: ['alaska', 'northwest-territory','ontario','western-usa']},
            {countryName: 'Argentina', country: 'argentina', continent: 'South America', color: 'S', borders: ['brazil', 'peru']},
            {countryName: 'Brazil', country: 'brazil', continent: 'South America', color: 'S', borders: ['veneseulea', 'argentina','peru','north-africa']},
            {countryName: 'Central America', country: 'central-america', continent: 'North America', color: 'W', borders: ['veneseulea', 'eastern-usa','western-usa']},
            {countryName: 'China', country: 'china', continent: 'Asia', color: 'G', borders: ['mongolia', 'siberia','ural','afghanistan','india','siam']},
            {countryName: 'Congo', country: 'congo', continent: 'Africa', color: 'B', borders: ['east-africa', 'south-africa','north-africa']},
            {countryName: 'East Africa', country: 'east-africa', continent: 'Africa', color: 'B', borders: ['egypt', 'north-africa','congo','south-africa','madagascar','middle-east']},
            {countryName: 'Eastern Australia', country: 'eastern-australia', continent: 'Australia', color: 'R', borders: ['new-guinea', 'western-australia']},
            {countryName: 'Eastern USA', country: 'eastern-usa', continent: 'North America', color: 'W', borders: ['quebec', 'ontario','western-usa','central-america']},
            {countryName: 'Egypt', country: 'egypt', continent: 'Africa', color: 'B', borders: ['middle-east', 'southern-europe','north-africa','east-africa']},
            {countryName: 'Great Britan', country: 'great-britan', continent: 'Europe', color: 'U', borders: ['iceland', 'scandanavia','northern-europe','western-europe']},
            {countryName: 'Greenland', country: 'greenland', continent: 'North America', color: 'W', borders: ['northwest-territory', 'ontario','quebec','iceland']},
            {countryName: 'Iceland', country: 'iceland', continent: 'Europe', color: 'U', borders: ['greenland', 'scandanavia','great-britan']},
            {countryName: 'India', country: 'india', continent: 'Asia', color: 'G', borders: ['middle-east', 'afghanistan','china','siam']},
            {countryName: 'Indonesia', country: 'indonesia', continent: 'Australia', color: 'R', borders: ['siam', 'new-guinea','western-australia']},
            {countryName: 'Irkutsk', country: 'irkutsk', continent: 'Asia', color: 'G', borders: ['yakutsk', 'kamchatka','mongolia','siberia']},
            {countryName: 'Japan', country: 'japan', continent: 'Asia', color: 'G', borders: ['mongolia', 'kamchatka']},
            {countryName: 'Kamchatka', country: 'kamchatka', continent: 'Asia', color: 'G', borders: ['japan', 'alaska','mongolia','irkutsk','yakutsk']},
            {countryName: 'Madagascar', country: 'madagascar', continent: 'Africa', color: 'B', borders: ['south-africa', 'east-africa']},
            {countryName: 'Middle East', country: 'middle-east', continent: 'Asia', color: 'G', borders: ['east-africa', 'egypt','southern-europe','ukraine','afghanistan','india']},
            {countryName: 'Mongolia', country: 'mongolia', continent: 'Asia', color: 'G', borders: ['japan', 'kamchatka','irkutsk','siberia','china']},
            {countryName: 'New Guinea', country: 'new-guinea', continent: 'Australia', color: 'R', borders: ['indonesia', 'eastern-australia','western-australia']},
            {countryName: 'North Africa', country: 'north-africa', continent: 'Africa', color: 'B', borders: ['congo', 'brazil','western-europe','southern-europe','egypt','east-africa']},
            {countryName: 'Northern Europe', country: 'northern-europe', continent: 'Europe', color: 'U', borders: ['great-britan', 'scandanavia','ukraine','southern-europe','western-europe']},
            {countryName: 'Northwest Territory', country: 'northwest-territory', continent: 'North America', color: 'W', borders: ['alaska', 'alberta','greenland','ontario']},
            {countryName: 'Ontario', country: 'ontario', continent: 'North America', color: 'W', borders: ['quebec', 'eastern-usa','alberta','western-usa','northwest-territory','greenland']},
            {countryName: 'Peru', country: 'peru', continent: 'South America', color: 'S', borders: ['brazil', 'argentina','veneseulea']},
            {countryName: 'Quebec', country: 'quebec', continent: 'North America', color: 'W', borders: ['eastern-usa', 'ontario','greenland']},
            {countryName: 'Scandanavia', country: 'scandanavia', continent: 'Europe', color: 'U', borders: ['iceland', 'great-britan','northern-europe','ukraine']},
            {countryName: 'Siam', country: 'siam', continent: 'Asia', color: 'G', borders: ['china', 'india','indonesia']},
            {countryName: 'Siberia', country: 'siberia', continent: 'Asia', color: 'G', borders: ['china', 'ural','mongolia','irkutsk','yakutsk']},
            {countryName: 'South Africa', country: 'south-africa', continent: 'Africa', color: 'B', borders: ['congo', 'east-africa','madagascar']},
            {countryName: 'Southern Europe', country: 'southern-europe', continent: 'Europe', color: 'U', borders: ['western-europe', 'northern-europe','ukraine','middle-east','egypt','north-africa']},
            {countryName: 'Ukraine', country: 'ukraine', continent: 'Europe', color: 'U', borders: ['scandanavia', 'northern-europe','southern-europe','middle-east','afghanistan','ural']},
            {countryName: 'Ural', country: 'ural', continent: 'Asia', color: 'G', borders: ['ukraine', 'afghanistan','china','siberia']},
            {countryName: 'Veneseulea', country: 'veneseulea', continent: 'South America', color: 'S', borders: ['brazil', 'peru','central-america']},
            {countryName: 'Western Australia', country: 'western-australia', continent: 'Australia', color: 'R', borders: ['eastern-australia', 'indonesia','new-guinea']},
            {countryName: 'Western Europe', country: 'western-europe', continent: 'Europe', color: 'U', borders: ['great-britan', 'northern-europe','north-africa','southern-europe']},
            {countryName: 'Western USA', country: 'western-usa', continent: 'North America', color: 'W', borders: ['alberta', 'ontario','central-america','eastern-usa']},
            {countryName: 'Yakutsk', country: 'yakutsk', continent: 'Asia', color: 'G', borders: ['irkutsk', 'kamchatka','siberia']}
        ]
    },
    playerInfo: {
        player1: {
            playerName: "Player1",
            playerSupplyPoints: 0,
            playerDecklist: [
                {deckName: "Everything Burns", deckColors: "RG"},
                {deckName: "Evil Eye", deckColors: "B"},
                {deckName: "Exsanguimator", deckColors: "WUBRG"},
                {deckName: "Fall of Troy", deckColors: "W"},
                {deckName: "Fat Cobra", deckColors: "G"},
                {deckName: "Ferngully's Payback", deckColors: "UBG"},
                {deckName: "Float like a Butterfly, Sting like a Bee", deckColors: "WUBRG"},
                {deckName: "another deck", deckColors: "WUBRG"},
                {deckName: "For Honor and Valor", deckColors: "W"},
                {deckName: "For the Cause", deckColors: "W"},
                {deckName: "Forged in Stone", deckColors: "W"},
                {deckName: "Frankenstein", deckColors: "B"},
                {deckName: "Frankie's Question", deckColors: "WU"},
                {deckName: "Ghave's Growth", deckColors: "WBG"},
                {deckName: "Gin", deckColors: "WR"},
                {deckName: "Goblins Vs", deckColors: "R"},
                {deckName: "apl1 Golgari", deckColors: "BG"},
                {deckName: "Good Will", deckColors: "U"},
                {deckName: "Graveborn", deckColors: "WUBRG"},
                {deckName: "Great Forest Emergence", deckColors: "G"},
                {deckName: "Green Acres", deckColors: "WG"},
                {deckName: "Green Beets", deckColors: "G"},
                {deckName: "Green Giant", deckColors: "G"},
                {deckName: "Green Manaburn", deckColors: "G"},
                {deckName: "Guardians of the Muck", deckColors: "WUBG"},
                {deckName: "Guardians of the Wild", deckColors: "G"},
                {deckName: "Guided By Nature", deckColors: "G"},
                {deckName: "66% of the Time, it Works Every Time", deckColors: "R"},
                {deckName: "Justice and Fury", deckColors: "WRG"},
                {deckName: "Angels", deckColors: "W"},
                {deckName: "Assemble the Doomsday Machine", deckColors: "WUB"},
                {deckName: "Bring About the Undead Apocalypse", deckColors: "BR"},
                {deckName: "Scorch the World with Dragonsfire", deckColors: "BR"},
                {deckName: "Trample Civilization Underfoot", deckColors: "WG"},
                {deckName: "Army of Entropy", deckColors: "BR"},
                {deckName: "Aura Masters", deckColors: "WU"},
                {deckName: "Azorus Ascendant", deckColors: "WU"},
                {deckName: "Back to the Graveyard", deckColors: "UB"},
                {deckName: "Bailfire Liege", deckColors: "WR"},
                {deckName: "Barrage", deckColors: "RG"},
                {deckName: "Battalion", deckColors: "W"},
                {deckName: "Bestow upon You", deckColors: "WB"},
                {deckName: "Big Blue", deckColors: "UBG"},
                {deckName: "Big Red Blast Fest", deckColors: "R"},
                {deckName: "Blizak and Wizite", deckColors: "WB"},
                {deckName: "Boggart's Feast", deckColors: "BR"},
                {deckName: "Bogs Brew", deckColors: "B"},
                {deckName: "aBouncefest", deckColors: "WUB"},
                {deckName: "Bright Future", deckColors: "B"},
                {deckName: "Broken the 20th Level of Enlightenment", deckColors: "U"},
                {deckName: "Burokku Sa Renal Seishin", deckColors: "U"},
                {deckName: "Buybacks A Bitch", deckColors: "WBG"},
                {deckName: "Burn and Destroy", deckColors: "R"},
                {deckName: "Charmed Existense", deckColors: "WUBRG"},
                {deckName: "Cheap Artifacts", deckColors: "WUBR"},
                {deckName: "Code of the Orzhov", deckColors: "WB"},
                {deckName: "aCoalition", deckColors: "WUBRG"},
                {deckName: "Command Your Creatures", deckColors: "WG"},
                {deckName: "Evasive Maneuvers", deckColors: "WUG"},
                {deckName: "Eternal Bargain", deckColors: "WUB"},
                {deckName: "Mirror Mastery", deckColors: "URG"},
                {deckName: "Nature of the Beast", deckColors: "WRG"},
                {deckName: "Peer Through Time", deckColors: "W"},
                {deckName: "Power Hungry", deckColors: "BRG"},
                {deckName: "Guided by Nature", deckColors: "G"},
                {deckName: "Mindseize", deckColors: "UBR"},
                {deckName: "Sworn to Darkness", deckColors: "B"},
                {deckName: "Critical Mass", deckColors: "BR"},
                {deckName: "Dark Cycle", deckColors: "WB"},
                {deckName: "Death March", deckColors: "BG"},
                {deckName: "Demons", deckColors: "B"},
                {deckName: "Dimir's Intrigues", deckColors: "UB"},
                {deckName: "Dimir's Revenge", deckColors: "UB"},
                {deckName: "Distorted Reality Pool", deckColors: "U"},
                {deckName: "Dragons", deckColors: "R"},
                {deckName: "Elemental's Path", deckColors: "WUBRG"},
                {deckName: "Elvish Predication", deckColors: "G"},
                {deckName: "Duty and Protection", deckColors: "W"},
                {deckName: "Everybody Dies", deckColors: "BR"},
                {deckName: "aEvolutions A Happin'", deckColors: "BG"},
                {deckName: "Ev're Day I'm Shufflin'", deckColors: "BR"},
                {deckName: "Eye of Distortion", deckColors: "WU"},
                {deckName: "Fate", deckColors: "UG"},
                {deckName: "Flayer of the Hartbound", deckColors: "RG"},
                {deckName: "Flippin' Crazy", deckColors: "BR"},
                {deckName: "From the Graveyard", deckColors: "UB"},
                {deckName: "Fury", deckColors: "R"},
                {deckName: "George's Special Forces", deckColors: "UB"},
                {deckName: "Goblin", deckColors: "R"},
                {deckName: "Going Rouge", deckColors: "UB"},
                {deckName: "Golgari", deckColors: "BG"},
                {deckName: "Green Slivers", deckColors: "G"},
                {deckName: "Grull Weilding", deckColors: "RG"},
                {deckName: "Ferocity and Growth", deckColors: "G"},
                {deckName: "Guscloke", deckColors: "WU"},
                {deckName: "Heath Nelson", deckColors: "WUBRG"},
                {deckName: "Hero", deckColors: "WR"},
                {deckName: "Hollow Ground", deckColors: "UG"},
                {deckName: "Hope's Crusade", deckColors: "W"},
                {deckName: "I Have Crabs", deckColors: "U"},
                {deckName: "Northern Horde", deckColors: "R"},
                {deckName: "Obsessive Madness", deckColors: "BRG"},
                {deckName: "Octopie Buttkrakens and Serpents Oh My!", deckColors: "U"},
                {deckName: "One For All", deckColors: "WUBRG"},
                {deckName: "Orc Hordes", deckColors: "WBRG"},
                {deckName: "Ordeals Aplenty", deckColors: "WUBRG"}
            ]
        },
        player2: {
            playerName: "Player2",
            playerSupplyPoints: 0,
            playerDecklist: [
                {deckName: "I Have Crabs", deckColors: "U"},
                {deckName: "Northern Horde", deckColors: "R"},
                {deckName: "Obsessive Madness", deckColors: "BRG"},
                {deckName: "Octopie Buttkrakens and Serpents Oh My!", deckColors: "U"},
                {deckName: "One For All", deckColors: "WUBRG"},
                {deckName: "aOrc Hordes", deckColors: "WBRG"},
                {deckName: "Ordeals Aplenty", deckColors: "WUBRG"},
                {deckName: "Pack Hunt", deckColors: "BG"},
                {deckName: "Pain Scramble", deckColors: "BR"},
                {deckName: "apl2 Peer Through Time", deckColors: "U"},
                {deckName: "Phyrexia", deckColors: "B"},
                {deckName: "Pianna Roams", deckColors: "W"},
                {deckName: "Political Puppets", deckColors: "WUR"},
                {deckName: "Polluted Minds", deckColors: "UBR"},
                {deckName: "Pon Farr", deckColors: "UBR"},
                {deckName: "Power Hungry", deckColors: "BRG"},
                {deckName: "Primordial Hunger", deckColors: "RG"},
                {deckName: "Rabid Dancer", deckColors: "WR"},
                {deckName: "Rabid Wombat", deckColors: "G"},
                {deckName: "Rafiq of the Many", deckColors: "WUG"},
                {deckName: "Rage With the Machine", deckColors: "WUBR"},
                {deckName: "Ramirez DePietro", deckColors: "UB"},
                {deckName: "Rattlin Bog", deckColors: "B"},
                {deckName: "Recycled Life", deckColors: "BG"},
                {deckName: "Red Wizard's Doom", deckColors: "WU"},
                {deckName: "Relentless Rats", deckColors: "B"},
                {deckName: "Revenge of the Orb", deckColors: "WU"},
                {deckName: "Rohgahh", deckColors: "BR"},
                {deckName: "Sands of Life", deckColors: "W"},
                {deckName: "Savage Auras", deckColors: "WG"},
                {deckName: "Scalpelexis Exists", deckColors: "U"},
                {deckName: "Scrambled Eggs", deckColors: "WR"},
                {deckName: "Secret Scrolls", deckColors: "U"},
                {deckName: "Senju Hashirama Clan", deckColors: "UG"},
                {deckName: "Serra Angel Speed Bump", deckColors: "UBR"},
                {deckName: "Seven Seas", deckColors: "U"},
                {deckName: "Shady Business", deckColors: "B"},
                {deckName: "Siren Gwendlyn", deckColors: "UBR"},
                {deckName: "Siren Merieke Ri Berit", deckColors: "WUB"},
                {deckName: "Siren Rubinia", deckColors: "WUG"},
                {deckName: "Sky is Falling", deckColors: "UG"},
                {deckName: "aSlip and Slide", deckColors: "WUG"},
                {deckName: "Slumgolem Casserole", deckColors: "WUBG"},
                {deckName: "Snakes on a Bow", deckColors: "UBG"},
                {deckName: "Sparkley Bits", deckColors: "U"},
                {deckName: "SPECTRE", deckColors: "B"},
                {deckName: "Speed Vs", deckColors: "WBR"},
                {deckName: "Spread the Sickness", deckColors: "BRG"},
                {deckName: "Starre Night", deckColors: "WU"},
                {deckName: "Stealthy Attack", deckColors: "WUBRG"},
                {deckName: "Stewards of Kher", deckColors: "BRG"},
                {deckName: "Summer Expedition", deckColors: "RG"},
                {deckName: "Sworn to Darkness", deckColors: "B"},
                {deckName: "Tamanoa Sunrise", deckColors: "WRG"},
                {deckName: "Tetsuo Umezawa", deckColors: "UBR"},
                {deckName: "Texas Justice", deckColors: "WB"},
                {deckName: "That Deck", deckColors: "UB"},
                {deckName: "The Avengers", deckColors: "WU"},
                {deckName: "The Coalition", deckColors: "WUBRG"},
                {deckName: "The Hive", deckColors: "WUBRG"},
                {deckName: "Thriss", deckColors: "G"},
                {deckName: "Tiamat", deckColors: "WUBRG"},
                {deckName: "Tinkering Gnomes", deckColors: "WUBRG"},
                {deckName: "Top Gun", deckColors: "WU"},
                {deckName: "Toshiro's Pact", deckColors: "WUBRG"},
                {deckName: "Tour De Jour", deckColors: "WUBRG"},
                {deckName: "Traitor's of Glissa", deckColors: "BG"},
                {deckName: "Transformers", deckColors: "W"},
                {deckName: "aTriumph of the Orb", deckColors: "BG"},
                {deckName: "Trostani's Grove", deckColors: "WG"},
                {deckName: "Trumpets of Peace", deckColors: "W"},
                {deckName: "Trumpets of War", deckColors: "WR"},
                {deckName: "Twisted Bramble Bugs", deckColors: "UG"},
                {deckName: "Uril the Miststalker", deckColors: "WRG"},
                {deckName: "War", deckColors: "R"},
                {deckName: "War Never Changes", deckColors: "R"},
                {deckName: "Weezer", deckColors: "U"},
                {deckName: "Weird Science", deckColors: "UBRG"},
                {deckName: "Werewolf Pack", deckColors: "B"},
                {deckName: "What Is Real?", deckColors: "U"},
                {deckName: "Whimsical Musings of Delight", deckColors: "URG"},
                {deckName: "Who's The Bosh", deckColors: "R"},
                {deckName: "Wild BBQ", deckColors: "RG"},
                {deckName: "Deckmaster Richard Garfield", deckColors: "RG"},
                {deckName: "Democratic Conspiracy", deckColors: "WUBRG"},
                {deckName: "Denial of Will", deckColors: "UB"},
                {deckName: "Devour for Power", deckColors: "WBG"},
                {deckName: "Diaoshan Artful Beauty", deckColors: "R"},
                {deckName: "Doom Men of the Moon", deckColors: "WURG"},
                {deckName: "Double or Nothing", deckColors: "WUBRG"},
                {deckName: "Dragon Fury", deckColors: "UR"},
                {deckName: "Dragon Mountain", deckColors: "R"},
                {deckName: "Dragon's Horde", deckColors: "R"},
                {deckName: "Drop of Daylight", deckColors: "WUBRG"},
                {deckName: "Dwarven Thunder", deckColors: "R"},
                {deckName: "Elves of Fury", deckColors: "URG"},
                {deckName: "Elves of the Chosen", deckColors: "G"},
                {deckName: "Elves Vs", deckColors: "G"},
                {deckName: "Empire Strikes Back", deckColors: "UR"},
                {deckName: "End of the World", deckColors: "W"},
                {deckName: "Enter Shahrazad", deckColors: "WB"},
                {deckName: "Erupt and Overwhelm", deckColors: "R"},
                {deckName: "Eternal Bargain", deckColors: "WUB"},
                {deckName: "Evade and Shimmer", deckColors: "WU"},
                {deckName: "Evasive Maneuvers", deckColors: "WUG"},
                {deckName: "Adun Oakenshield", deckColors: "BRG"},
                {deckName: "Age of Ice", deckColors: "WUBRG"},
                {deckName: "Allies Aplenty", deckColors: "WUBRG"},
                {deckName: "Alms for the Cure", deckColors: "WB"},
                {deckName: "Ancestors", deckColors: "WU"},
                {deckName: "Angel's Grace", deckColors: "W"},
                {deckName: "Atog Atog", deckColors: "WUBRG"},
                {deckName: "Attack of the Clones", deckColors: "UG"},
                {deckName: "Auroch Herd", deckColors: "G"},
                {deckName: "Balthazor", deckColors: "WUBRG"},
                {deckName: "Balthazor's Groupies", deckColors: "WUBRG"},
                {deckName: "Balthazor's Minions", deckColors: "B"},
                {deckName: "Balthor's Minions", deckColors: "B"},
                {deckName: "Baru for You", deckColors: "G"},
                {deckName: "Beatdown for Hire", deckColors: "B"},
                {deckName: "Beeble Beatdown", deckColors: "U"},
                {deckName: "Big Blue", deckColors: "U"},
                {deckName: "Big Green", deckColors: "G"},
                {deckName: "Big White", deckColors: "W"},
                {deckName: "Bird is the Word", deckColors: "WU"},
                {deckName: "Blight of the Fens", deckColors: "B"},
                {deckName: "Bling", deckColors: "WBG"}
            ]
        },
        player3: {
            playerName: "Player3",
            playerSupplyPoints: 0,
            playerDecklist: [
                {deckName: "Big Blue", deckColors: "U"},
                {deckName: "Big Green", deckColors: "G"},
                {deckName: "Big White", deckColors: "W"},
                {deckName: "Bird is the Word", deckColors: "WU"},
                {deckName: "Blight of the Fens", deckColors: "B"},
                {deckName: "Bling", deckColors: "WBG"},
                {deckName: "Blitz Kreig", deckColors: "RG"},
                {deckName: "Blood Carnival", deckColors: "BR"},
                {deckName: "Bones", deckColors: "WUBRG"},
                {deckName: "apl3 Brain Scramble", deckColors: "UR"},
                {deckName: "aBruna", deckColors: "WU"},
                {deckName: "Built From Scratch", deckColors: "R"},
                {deckName: "Bump in the Night", deckColors: "B"},
                {deckName: "Burn the Earth", deckColors: "R"},
                {deckName: "Burning Fury of a Thousand Suns", deckColors: "R"},
                {deckName: "Champions of the Pit - Initiation Deck", deckColors: "WBR"},
                {deckName: "Chaos Reigns", deckColors: "WUBRG"},
                {deckName: "Chatter of the Squirrel", deckColors: "G"},
                {deckName: "Cheap Goblins", deckColors: "R"},
                {deckName: "Chill Pauper", deckColors: "WU"},
                {deckName: "Circle of Life", deckColors: "WUBRG"},
                {deckName: "Color in the Beatdown", deckColors: "WUBRG"},
                {deckName: "Combat Mastery", deckColors: "W"},
                {deckName: "Counter Punch", deckColors: "UBG"},
                {deckName: "Coven of Nine", deckColors: "WUBR"},
                {deckName: "Crab People", deckColors: "UB"},
                {deckName: "Crackling Goblins", deckColors: "R"},
                {deckName: "Crazy Goblins", deckColors: "R"},
                {deckName: "Crazy Train", deckColors: "UR"},
                {deckName: "Croaking Goblins", deckColors: "R"},
                {deckName: "Crunchy Goblins", deckColors: "R"},
                {deckName: "Cult of Nefarox", deckColors: "B"},
                {deckName: "Cunning Vs", deckColors: "WUR"},
                {deckName: "Dakkon Blackblade", deckColors: "WUB"},
                {deckName: "Damage for Breakfast", deckColors: "WR"},
                {deckName: "Darien's Legacy", deckColors: "W"},
                {deckName: "aDark Devotion", deckColors: "UBR"},
                {deckName: "Deal With the Devil", deckColors: "R"},
                {deckName: "Deathklok", deckColors: "UBR"},
                {deckName: "Deckmaster Jon Finkel", deckColors: "BR"},
                {deckName: "Deckmaster Richard Garfield", deckColors: "RG"},
                {deckName: "Democratic Conspiracy", deckColors: "WUBRG"},
                {deckName: "Denial of Will", deckColors: "UB"},
                {deckName: "Devour for Power", deckColors: "WBG"},
                {deckName: "Diaoshan Artful Beauty", deckColors: "R"},
                {deckName: "Doom Men of the Moon", deckColors: "WURG"},
                {deckName: "Double or Nothing", deckColors: "WUBRG"},
                {deckName: "Dragon Fury", deckColors: "UR"},
                {deckName: "Dragon Mountain", deckColors: "R"},
                {deckName: "Dragon's Horde", deckColors: "R"},
                {deckName: "Drop of Daylight", deckColors: "WUBRG"},
                {deckName: "Dwarven Thunder", deckColors: "R"},
                {deckName: "Elves of Fury", deckColors: "URG"},
                {deckName: "Elves of the Chosen", deckColors: "G"},
                {deckName: "Elves Vs", deckColors: "G"},
                {deckName: "Empire Strikes Back", deckColors: "UR"},
                {deckName: "End of the World", deckColors: "W"},
                {deckName: "Enter Shahrazad", deckColors: "WB"},
                {deckName: "Erupt and Overwhelm", deckColors: "R"},
                {deckName: "Eternal Bargain", deckColors: "WUB"},
                {deckName: "Evade and Shimmer", deckColors: "WU"},
                {deckName: "Evasive Maneuvers", deckColors: "WUG"},
                {deckName: "Everything Burns", deckColors: "RG"},
                {deckName: "Evil Eye", deckColors: "B"},
                {deckName: "Exsanguimator", deckColors: "WUBRG"},
                {deckName: "Fall of Troy", deckColors: "W"},
                {deckName: "Fat Cobra", deckColors: "G"},
                {deckName: "Ferngully's Payback", deckColors: "UBG"},
                {deckName: "aFloat like a Butterfly, Sting like a Bee", deckColors: "WUBRG"},
                {deckName: "another deck", deckColors: "WUBRG"},
                {deckName: "For Honor and Valor", deckColors: "W"},
                {deckName: "For the Cause", deckColors: "W"},
                {deckName: "Forged in Stone", deckColors: "W"},
                {deckName: "Frankenstein", deckColors: "B"},
                {deckName: "Frankie's Question", deckColors: "WU"},
                {deckName: "Ghave's Growth", deckColors: "WBG"},
                {deckName: "Gin", deckColors: "WR"},
                {deckName: "Goblins Vs", deckColors: "R"},
                {deckName: "Golgari", deckColors: "BG"},
                {deckName: "Good Will", deckColors: "U"},
                {deckName: "Graveborn", deckColors: "WUBRG"},
                {deckName: "Great Forest Emergence", deckColors: "G"},
                {deckName: "Green Acres", deckColors: "WG"},
                {deckName: "Green Beets", deckColors: "G"},
                {deckName: "Green Giant", deckColors: "G"},
                {deckName: "Green Manaburn", deckColors: "G"},
                {deckName: "Guardians of the Muck", deckColors: "WUBG"},
                {deckName: "Guardians of the Wild", deckColors: "G"},
                {deckName: "Guided By Nature", deckColors: "G"},
                {deckName: "Hakunin", deckColors: "WUBRG"},
                {deckName: "Happy Days", deckColors: "WG"},
                {deckName: "Hazezom Tamar", deckColors: "WRG"},
                {deckName: "Heavenly Inferno", deckColors: "WBR"},
                {deckName: "Hidden Phoenix", deckColors: "WRG"},
                {deckName: "Hippie Denial", deckColors: "B"},
                {deckName: "Hive's Breath", deckColors: "U"},
                {deckName: "Hive's Crusade", deckColors: "W"},
                {deckName: "Hive's Diversity", deckColors: "WUBRG"},
                {deckName: "Hive's Growth", deckColors: "G"},
                {deckName: "Hive's Neglect", deckColors: "WUBRG"},
                {deckName: "Hive's Rage", deckColors: "R"},
                {deckName: "Hive's Shadow", deckColors: "B"},
                {deckName: "Holy Crusade", deckColors: "WB"},
                {deckName: "Holy Relics", deckColors: "WB"},
                {deckName: "Honden of The Myojin", deckColors: "WUBRG"},
                {deckName: "House of Pain by George Baxter", deckColors: "BRG"},
                {deckName: "I am Legend", deckColors: "WUBRG"},
                {deckName: "Ice Kitten", deckColors: "U"},
                {deckName: "Ice Scraper", deckColors: "U"},
                {deckName: "iSpell", deckColors: "WUBRG"},
                {deckName: "It Came From the Malestrom", deckColors: "URG"},
                {deckName: "Ivy League", deckColors: "U"},
                {deckName: "Izzet", deckColors: "UR"},
                {deckName: "Jhoira", deckColors: "UR"},
                {deckName: "John's Modern", deckColors: "WRG"},
                {deckName: "John's Ocean Critters", deckColors: "WU"},
                {deckName: "Juicy Fruit", deckColors: "WUBRG"},
                {deckName: "Junkyard", deckColors: "W"},
                {deckName: "Justin Sane", deckColors: "N"},
                {deckName: "Justin Time", deckColors: "N"},
                {deckName: "Karona", deckColors: "WUBRG"},
                {deckName: "Knowledge is Power", deckColors: "U"},
                {deckName: "Life Not Unlived", deckColors: "WUBRG"},
                {deckName: "Light and Fury", deckColors: "WR"},
                {deckName: "Lim-Dul's Oasis", deckColors: "BRG"},
                {deckName: "Mad Scientist", deckColors: "UB"},
                {deckName: "Madara Uchia Clan", deckColors: "B"},
                {deckName: "Marath", deckColors: "WRG"},
                {deckName: "Maraxus", deckColors: "R"},
                {deckName: "Master of the Slaves", deckColors: "WUBR"},
                {deckName: "Mavrick", deckColors: "UBR"},
                {deckName: "Medic!", deckColors: "W"},
                {deckName: "Mermaider", deckColors: "WU"},
                {deckName: "Michael's Affinity", deckColors: "WUBRG"},
                {deckName: "Michael's Dragons", deckColors: "BRG"},
                {deckName: "Michael's Madness", deckColors: "BG"},
                {deckName: "Michael's Norin", deckColors: "R"},
                {deckName: "Michael's Psychatog", deckColors: "UB"},
                {deckName: "Michael's Reanimator", deckColors: "WUBRG"},
                {deckName: "Michael's Slivers", deckColors: "WUBRG"},
                {deckName: "Michael's Tezzeret", deckColors: "UB"},
                {deckName: "Michael's Zombies", deckColors: "B"},
                {deckName: "Windseeker Hillbillies", deckColors: "WRG"},
                {deckName: "Witch Hunt", deckColors: "B"},
                {deckName: "Wolf Pack", deckColors: "RG"},
                {deckName: "Wombat Wannabe", deckColors: "WG"},
                {deckName: "Wooz's Deck of Ooze", deckColors: "UBRG"},
                {deckName: "Wort", deckColors: "BR"},
                {deckName: "Yamazaki Clan", deckColors: "UR"},
                {deckName: "Yellowstone", deckColors: "WURG"},
                {deckName: "You Only Live Twice", deckColors: "G"},
                {deckName: "Zedruu", deckColors: "WUR"},
                {deckName: "Zuberi", deckColors: "W"},
                {deckName: "Zur the Enchanter", deckColors: "WUB"},
                {deckName: "Nath", deckColors: "BG"},
                {deckName: "Nature of the Beast", deckColors: "WRG"},
                {deckName: "Nick's Illusionary Dreadnought", deckColors: "WU"}                
            ]
        },
        player4: {
            playerName: "Player4",
            playerSupplyPoints: 0,
            playerDecklist: [
                {deckName: "Wort", deckColors: "BR"},
                {deckName: "Yamazaki Clan", deckColors: "UR"},
                {deckName: "Yellowstone", deckColors: "WURG"},
                {deckName: "You Only Live Twice", deckColors: "G"},
                {deckName: "Zedruu", deckColors: "WUR"},
                {deckName: "Zuberi", deckColors: "W"},
                {deckName: "aZur the Enchanter", deckColors: "WUB"},
                {deckName: "Nath", deckColors: "BG"},
                {deckName: "Nature of the Beast", deckColors: "WRG"},
                {deckName: "Nick's Illusionary Dreadnought", deckColors: "WU"},
                {deckName: "Night of the Ninja", deckColors: "UB"},
                {deckName: "Nightmare's Reward", deckColors: "B"},
                {deckName: "Niv-Mizzet", deckColors: "UR"},
                {deckName: "Niv's Rage", deckColors: "WUBRG"},
                {deckName: "Norin", deckColors: "R"},
                {deckName: "Northern Horde", deckColors: "R"},
                {deckName: "Obsessive Madness", deckColors: "BRG"},
                {deckName: "Octopie Buttkrakens and Serpents Oh My!", deckColors: "U"},
                {deckName: "One For All", deckColors: "WUBRG"},
                {deckName: "apl4 Orc Hordes", deckColors: "WBRG"},
                {deckName: "Ordeals Aplenty", deckColors: "WUBRG"},
                {deckName: "Pack Hunt", deckColors: "BG"},
                {deckName: "Pain Scramble", deckColors: "BR"},
                {deckName: "Peer Through Time", deckColors: "U"},
                {deckName: "Phyrexia", deckColors: "B"},
                {deckName: "Pianna Roams", deckColors: "W"},
                {deckName: "Political Puppets", deckColors: "WUR"},
                {deckName: "Polluted Minds", deckColors: "UBR"},
                {deckName: "Pon Farr", deckColors: "UBR"},
                {deckName: "Power Hungry", deckColors: "BRG"},
                {deckName: "Primordial Hunger", deckColors: "RG"},
                {deckName: "Rabid Dancer", deckColors: "WR"},
                {deckName: "Rabid Wombat", deckColors: "G"},
                {deckName: "Rafiq of the Many", deckColors: "WUG"},
                {deckName: "Rage With the Machine", deckColors: "WUBR"},
                {deckName: "Ramirez DePietro", deckColors: "UB"},
                {deckName: "Rattlin Bog", deckColors: "B"},
                {deckName: "Recycled Life", deckColors: "BG"},
                {deckName: "Red Wizard's Doom", deckColors: "WU"},
                {deckName: "Relentless Rats", deckColors: "B"},
                {deckName: "Revenge of the Orb", deckColors: "WU"},
                {deckName: "Rohgahh", deckColors: "BR"},
                {deckName: "Sands of Life", deckColors: "W"},
                {deckName: "Savage Auras", deckColors: "WG"},
                {deckName: "Scalpelexis Exists", deckColors: "U"},
                {deckName: "aScrambled Eggs", deckColors: "WR"},
                {deckName: "Secret Scrolls", deckColors: "U"},
                {deckName: "Senju Hashirama Clan", deckColors: "UG"},
                {deckName: "Serra Angel Speed Bump", deckColors: "UBR"},
                {deckName: "Seven Seas", deckColors: "U"},
                {deckName: "Shady Business", deckColors: "B"},
                {deckName: "Siren Gwendlyn", deckColors: "UBR"},
                {deckName: "Siren Merieke Ri Berit", deckColors: "WUB"},
                {deckName: "Siren Rubinia", deckColors: "WUG"},
                {deckName: "Sky is Falling", deckColors: "UG"},
                {deckName: "Slip and Slide", deckColors: "WUG"},
                {deckName: "Slumgolem Casserole", deckColors: "WUBG"},
                {deckName: "Snakes on a Bow", deckColors: "UBG"},
                {deckName: "Sparkley Bits", deckColors: "U"},
                {deckName: "SPECTRE", deckColors: "B"},
                {deckName: "Speed Vs", deckColors: "WBR"},
                {deckName: "Spread the Sickness", deckColors: "BRG"},
                {deckName: "Starre Night", deckColors: "WU"},
                {deckName: "Stealthy Attack", deckColors: "WUBRG"},
                {deckName: "Stewards of Kher", deckColors: "BRG"},
                {deckName: "Summer Expedition", deckColors: "RG"},
                {deckName: "Sworn to Darkness", deckColors: "B"},
                {deckName: "Tamanoa Sunrise", deckColors: "WRG"},
                {deckName: "Tetsuo Umezawa", deckColors: "UBR"},
                {deckName: "Texas Justice", deckColors: "WB"},
                {deckName: "That Deck", deckColors: "UB"},
                {deckName: "The Avengers", deckColors: "WU"},
                {deckName: "The Coalition", deckColors: "WUBRG"},
                {deckName: "The Hive", deckColors: "WUBRG"},
                {deckName: "Thriss", deckColors: "G"},
                {deckName: "Tiamat", deckColors: "WUBRG"},
                {deckName: "Tinkering Gnomes", deckColors: "WUBRG"},
                {deckName: "Top Gun", deckColors: "WU"},
                {deckName: "Toshiro's Pact", deckColors: "WUBRG"},
                {deckName: "Tour De Jour", deckColors: "WUBRG"},
                {deckName: "Traitor's of Glissa", deckColors: "BG"},
                {deckName: "Transformers", deckColors: "W"},
                {deckName: "Triumph of the Orb", deckColors: "BG"},
                {deckName: "Trostani's Grove", deckColors: "WG"},
                {deckName: "Trumpets of Peace", deckColors: "W"},
                {deckName: "Trumpets of War", deckColors: "WR"},
                {deckName: "Twisted Bramble Bugs", deckColors: "UG"},
                {deckName: "Uril the Miststalker", deckColors: "WRG"},
                {deckName: "War", deckColors: "R"},
                {deckName: "War Never Changes", deckColors: "R"},
                {deckName: "aWeezer", deckColors: "U"},
                {deckName: "Weird Science", deckColors: "UBRG"},
                {deckName: "Werewolf Pack", deckColors: "B"},
                {deckName: "What Is Real?", deckColors: "U"},
                {deckName: "Whimsical Musings of Delight", deckColors: "URG"},
                {deckName: "Who's The Bosh", deckColors: "R"},
                {deckName: "Wild BBQ", deckColors: "RG"},
                {deckName: "Deckmaster Richard Garfield", deckColors: "RG"},
                {deckName: "Democratic Conspiracy", deckColors: "WUBRG"},
                {deckName: "Denial of Will", deckColors: "UB"},
                {deckName: "Devour for Power", deckColors: "WBG"},
                {deckName: "Diaoshan Artful Beauty", deckColors: "R"},
                {deckName: "Doom Men of the Moon", deckColors: "WURG"},
                {deckName: "Double or Nothing", deckColors: "WUBRG"},
                {deckName: "Dragon Fury", deckColors: "UR"},
                {deckName: "Dragon Mountain", deckColors: "R"},
                {deckName: "Dragon's Horde", deckColors: "R"},
                {deckName: "Drop of Daylight", deckColors: "WUBRG"},
                {deckName: "Dwarven Thunder", deckColors: "R"},
                {deckName: "Elves of Fury", deckColors: "URG"},
                {deckName: "Elves of the Chosen", deckColors: "G"},
                {deckName: "Elves Vs", deckColors: "G"},
                {deckName: "Empire Strikes Back", deckColors: "UR"},
                {deckName: "End of the World", deckColors: "W"},
                {deckName: "Enter Shahrazad", deckColors: "WB"},
                {deckName: "Erupt and Overwhelm", deckColors: "R"},
                {deckName: "Eternal Bargain", deckColors: "WUB"},
                {deckName: "Evade and Shimmer", deckColors: "WU"},
                {deckName: "Evasive Maneuvers", deckColors: "WUG"},
                {deckName: "Everything Burns", deckColors: "RG"},
                {deckName: "Evil Eye", deckColors: "B"},
                {deckName: "Exsanguimator", deckColors: "WUBRG"},
                {deckName: "Fall of Troy", deckColors: "W"},
                {deckName: "Fat Cobra", deckColors: "G"},
                {deckName: "Ferngully's Payback", deckColors: "UBG"},
                {deckName: "Float like a Butterfly, Sting like a Bee", deckColors: "WUBRG"},
                {deckName: "another deck", deckColors: "WUBRG"},
                {deckName: "For Honor and Valor", deckColors: "W"},
                {deckName: "For the Cause", deckColors: "W"},
                {deckName: "Forged in Stone", deckColors: "W"},
                {deckName: "Frankenstein", deckColors: "B"},
                {deckName: "Frankie's Question", deckColors: "WU"},
                {deckName: "Ghave's Growth", deckColors: "WBG"},
                {deckName: "Gin", deckColors: "WR"},
                {deckName: "Goblins Vs", deckColors: "R"},
                {deckName: "Golgari", deckColors: "BG"},
                {deckName: "Good Will", deckColors: "U"},
                {deckName: "Graveborn", deckColors: "WUBRG"},
                {deckName: "Great Forest Emergence", deckColors: "G"},
                {deckName: "Green Acres", deckColors: "WG"},
                {deckName: "Green Beets", deckColors: "G"},
                {deckName: "Green Giant", deckColors: "G"},
                {deckName: "Green Manaburn", deckColors: "G"},
                {deckName: "Guardians of the Muck", deckColors: "WUBG"},
                {deckName: "Guardians of the Wild", deckColors: "G"},
                {deckName: "Guided By Nature", deckColors: "G"},
                {deckName: "Hakunin", deckColors: "WUBRG"},
                {deckName: "Happy Days", deckColors: "WG"},
                {deckName: "Hazezom Tamar", deckColors: "WRG"},
                {deckName: "Heavenly Inferno", deckColors: "WBR"},
                {deckName: "Hidden Phoenix", deckColors: "WRG"},
                {deckName: "Hippie Denial", deckColors: "B"},
                {deckName: "Hive's Breath", deckColors: "U"},
                {deckName: "Hive's Crusade", deckColors: "W"},
                {deckName: "Hive's Diversity", deckColors: "WUBRG"},
                {deckName: "Hive's Growth", deckColors: "G"},
                {deckName: "Hive's Neglect", deckColors: "WUBRG"},
                {deckName: "Hive's Rage", deckColors: "R"},
                {deckName: "Hive's Shadow", deckColors: "B"},
                {deckName: "Holy Crusade", deckColors: "WB"},
                {deckName: "Holy Relics", deckColors: "WB"},
                {deckName: "Honden of The Myojin", deckColors: "WUBRG"},
                {deckName: "House of Pain by George Baxter", deckColors: "BRG"},
                {deckName: "I am Legend", deckColors: "WUBRG"},
                {deckName: "Ice Kitten", deckColors: "U"},
                {deckName: "Ice Scraper", deckColors: "U"}                
            ]
        },
        player5: {
            playerName: "Player5",
            playerSupplyPoints: 0,
            playerDecklist: [
                {deckName: "Holy Relics", deckColors: "WB"},
                {deckName: "Honden of The Myojin", deckColors: "WUBRG"},
                {deckName: "House of Pain by George Baxter", deckColors: "BRG"},
                {deckName: "I am Legend", deckColors: "WUBRG"},
                {deckName: "apl1 Ice Kitten", deckColors: "U"},
                {deckName: "Ice Scraper", deckColors: "U"},
                {deckName: "aiSpell", deckColors: "WUBRG"},
                {deckName: "It Came From the Malestrom", deckColors: "URG"},
                {deckName: "Ivy League", deckColors: "U"},
                {deckName: "Izzet", deckColors: "UR"},
                {deckName: "Jhoira", deckColors: "UR"},
                {deckName: "John's Modern", deckColors: "WRG"},
                {deckName: "John's Ocean Critters", deckColors: "WU"},
                {deckName: "Juicy Fruit", deckColors: "WUBRG"},
                {deckName: "Junkyard", deckColors: "W"},
                {deckName: "Justin Sane", deckColors: "N"},
                {deckName: "Justin Time", deckColors: "N"},
                {deckName: "Karona", deckColors: "WUBRG"},
                {deckName: "Knowledge is Power", deckColors: "U"},
                {deckName: "Life Not Unlived", deckColors: "WUBRG"},
                {deckName: "Light and Fury", deckColors: "WR"},
                {deckName: "Lim-Dul's Oasis", deckColors: "BRG"},
                {deckName: "Mad Scientist", deckColors: "UB"},
                {deckName: "Madara Uchia Clan", deckColors: "B"},
                {deckName: "Marath", deckColors: "WRG"},
                {deckName: "Maraxus", deckColors: "R"},
                {deckName: "Master of the Slaves", deckColors: "WUBR"},
                {deckName: "Mavrick", deckColors: "UBR"},
                {deckName: "Medic!", deckColors: "W"},
                {deckName: "Mermaider", deckColors: "WU"},
                {deckName: "Michael's Affinity", deckColors: "WUBRG"},
                {deckName: "Michael's Dragons", deckColors: "BRG"},
                {deckName: "Michael's Madness", deckColors: "BG"},
                {deckName: "Michael's Norin", deckColors: "R"},
                {deckName: "Michael's Psychatog", deckColors: "UB"},
                {deckName: "Michael's Reanimator", deckColors: "WUBRG"},
                {deckName: "Michael's Slivers", deckColors: "WUBRG"},
                {deckName: "Michael's Tezzeret", deckColors: "UB"},
                {deckName: "Michael's Zombies", deckColors: "B"},
                {deckName: "Minamo Namikaze Clan", deckColors: "U"},
                {deckName: "Mind Boggle", deckColors: "UB"},
                {deckName: "Mind Fog", deckColors: "G"},
                {deckName: "Mind Seize", deckColors: "UBR"},
                {deckName: "Mirror Mastery", deckColors: "URG"},
                {deckName: "Mirror Mirror", deckColors: "WUBRG"},
                {deckName: "apl5 Miscalculation", deckColors: "UB"},
                {deckName: "aMishra", deckColors: "UBR"},
                {deckName: "Monkey Business", deckColors: "RG"},
                {deckName: "Monks Of The Full Palm", deckColors: "URG"},
                {deckName: "Mythical Proportions", deckColors: "WUBRG"},
                {deckName: "Nantuko Knights", deckColors: "WG"},
                {deckName: "Nath", deckColors: "BG"},
                {deckName: "Nature of the Beast", deckColors: "WRG"},
                {deckName: "Nick's Illusionary Dreadnought", deckColors: "WU"},
                {deckName: "Night of the Ninja", deckColors: "UB"},
                {deckName: "Nightmare's Reward", deckColors: "B"},
                {deckName: "Niv-Mizzet", deckColors: "UR"},
                {deckName: "Niv's Rage", deckColors: "WUBRG"},
                {deckName: "Norin", deckColors: "R"},
                {deckName: "Northern Horde", deckColors: "R"},
                {deckName: "Obsessive Madness", deckColors: "BRG"},
                {deckName: "Octopie Buttkrakens and Serpents Oh My!", deckColors: "U"},
                {deckName: "One For All", deckColors: "WUBRG"},
                {deckName: "Orc Hordes", deckColors: "WBRG"},
                {deckName: "Ordeals Aplenty", deckColors: "WUBRG"},
                {deckName: "Pack Hunt", deckColors: "BG"},
                {deckName: "Pain Scramble", deckColors: "BR"},
                {deckName: "Peer Through Time", deckColors: "U"},
                {deckName: "Phyrexia", deckColors: "B"},
                {deckName: "Pianna Roams", deckColors: "W"},
                {deckName: "Political Puppets", deckColors: "WUR"},
                {deckName: "Polluted Minds", deckColors: "UBR"},
                {deckName: "Pon Farr", deckColors: "UBR"},
                {deckName: "Power Hungry", deckColors: "BRG"},
                {deckName: "Primordial Hunger", deckColors: "RG"},
                {deckName: "Rabid Dancer", deckColors: "WR"},
                {deckName: "Rabid Wombat", deckColors: "G"},
                {deckName: "Rafiq of the Many", deckColors: "WUG"},
                {deckName: "Rage With the Machine", deckColors: "WUBR"},
                {deckName: "Ramirez DePietro", deckColors: "UB"},
                {deckName: "Rattlin Bog", deckColors: "B"},
                {deckName: "Recycled Life", deckColors: "BG"},
                {deckName: "Red Wizard's Doom", deckColors: "WU"},
                {deckName: "Relentless Rats", deckColors: "B"},
                {deckName: "Revenge of the Orb", deckColors: "WU"},
                {deckName: "Rohgahh", deckColors: "BR"},
                {deckName: "Sands of Life", deckColors: "W"},
                {deckName: "Savage Auras", deckColors: "WG"},
                {deckName: "Scalpelexis Exists", deckColors: "U"},
                {deckName: "Scrambled Eggs", deckColors: "WR"},
                {deckName: "aSecret Scrolls", deckColors: "U"},
                {deckName: "Senju Hashirama Clan", deckColors: "UG"},
                {deckName: "Serra Angel Speed Bump", deckColors: "UBR"},
                {deckName: "Seven Seas", deckColors: "U"},
                {deckName: "Shady Business", deckColors: "B"},
                {deckName: "Siren Gwendlyn", deckColors: "UBR"},
                {deckName: "Siren Merieke Ri Berit", deckColors: "WUB"},
                {deckName: "Siren Rubinia", deckColors: "WUG"},
                {deckName: "Sky is Falling", deckColors: "UG"},
                {deckName: "Slip and Slide", deckColors: "WUG"},
                {deckName: "Slumgolem Casserole", deckColors: "WUBG"},
                {deckName: "Snakes on a Bow", deckColors: "UBG"},
                {deckName: "aSparkley Bits", deckColors: "U"},
                {deckName: "SPECTRE", deckColors: "B"},
                {deckName: "Speed Vs", deckColors: "WBR"},
                {deckName: "Spread the Sickness", deckColors: "BRG"},
                {deckName: "Starre Night", deckColors: "WU"},
                {deckName: "Stealthy Attack", deckColors: "WUBRG"},
                {deckName: "Stewards of Kher", deckColors: "BRG"},
                {deckName: "Summer Expedition", deckColors: "RG"},
                {deckName: "Sworn to Darkness", deckColors: "B"},
                {deckName: "Tamanoa Sunrise", deckColors: "WRG"},
                {deckName: "Tetsuo Umezawa", deckColors: "UBR"},
                {deckName: "Texas Justice", deckColors: "WB"},
                {deckName: "That Deck", deckColors: "UB"},
                {deckName: "The Avengers", deckColors: "WU"},
                {deckName: "The Coalition", deckColors: "WUBRG"},
                {deckName: "The Hive", deckColors: "WUBRG"},
                {deckName: "Thriss", deckColors: "G"},
                {deckName: "Tiamat", deckColors: "WUBRG"},
                {deckName: "Tinkering Gnomes", deckColors: "WUBRG"},
                {deckName: "Top Gun", deckColors: "WU"},
                {deckName: "Toshiro's Pact", deckColors: "WUBRG"},
                {deckName: "Tour De Jour", deckColors: "WUBRG"},
                {deckName: "Traitor's of Glissa", deckColors: "BG"},
                {deckName: "Transformers", deckColors: "W"},
                {deckName: "Triumph of the Orb", deckColors: "BG"},
                {deckName: "Trostani's Grove", deckColors: "WG"},
                {deckName: "Trumpets of Peace", deckColors: "W"},
                {deckName: "Trumpets of War", deckColors: "WR"},
                {deckName: "Twisted Bramble Bugs", deckColors: "UG"},
                {deckName: "Uril the Miststalker", deckColors: "WRG"},
                {deckName: "War", deckColors: "R"},
                {deckName: "War Never Changes", deckColors: "R"},
                {deckName: "Weezer", deckColors: "U"},
                {deckName: "Weird Science", deckColors: "UBRG"},
                {deckName: "Werewolf Pack", deckColors: "B"},
                {deckName: "What Is Real?", deckColors: "U"},
                {deckName: "Whimsical Musings of Delight", deckColors: "URG"},
                {deckName: "Who's The Bosh", deckColors: "R"},
                {deckName: "Wild BBQ", deckColors: "RG"},
                {deckName: "aDeckmaster Richard Garfield", deckColors: "RG"},
                {deckName: "Democratic Conspiracy", deckColors: "WUBRG"},
                {deckName: "Denial of Will", deckColors: "UB"},
                {deckName: "Devour for Power", deckColors: "WBG"},
                {deckName: "Diaoshan Artful Beauty", deckColors: "R"},
                {deckName: "Doom Men of the Moon", deckColors: "WURG"},
                {deckName: "Double or Nothing", deckColors: "WUBRG"},
                {deckName: "Dragon Fury", deckColors: "UR"},
                {deckName: "Dragon Mountain", deckColors: "R"},
                {deckName: "Dragon's Horde", deckColors: "R"},
                {deckName: "Drop of Daylight", deckColors: "WUBRG"},
                {deckName: "Dwarven Thunder", deckColors: "R"},
                {deckName: "Elves of Fury", deckColors: "URG"},
                {deckName: "Elves of the Chosen", deckColors: "G"},
                {deckName: "Elves Vs", deckColors: "G"},
                {deckName: "Empire Strikes Back", deckColors: "UR"},
                {deckName: "End of the World", deckColors: "W"},
                {deckName: "Enter Shahrazad", deckColors: "WB"},
                {deckName: "Erupt and Overwhelm", deckColors: "R"},
                {deckName: "Eternal Bargain", deckColors: "WUB"},
                {deckName: "Evade and Shimmer", deckColors: "WU"},
                {deckName: "Evasive Maneuvers", deckColors: "WUG"}                
            ]
        }
    }
};
